spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 12345
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

